# Improve colors
set -g default-terminal 'screen-256color'

# Set scrollback buffer to 10000
set -g history-limit 10000

# Customize the status line
set -g status-fg  white	
set -g status-bg  blue

# Change action key
unbind C-b
set-option -g prefix C-t

# Switch panes
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R

# Resize panes
bind  -r C-k resize-pane -U 5
bind  -r C-j resize-pane -D 5
bind  -r C-h resize-pane -L 5
bind  -r C-l resize-pane -R 5

# Enabling the mouse mode
setw -g mouse on

source-file ~/.config/tmux/statusline.conf

bind-key R source-file ~/.config/tmux/tmux.conf; display-message "Config successfully reloaded"
